### PR TITLE
fix(setup.py): support all python versions greater than 3.6

### PR DESCRIPTION
**Pull request by pierresouchay**
This will allow the project to be used in more recent projects

### CODE REVIEW

**Comment by fazaghifari** [comment]
Oh man,
I'm so sorry, didn't see this PR for almost one year. But it's done now 😉 

Thank you very much!

**Comment by pierresouchay** [comment]
Thank you @fazaghifari !

Would you mind publishing your library as well? That would be so great!

**Comment by fazaghifari** [comment]
It was already published in Pypi https://pypi.org/project/sobolsampling/.
But it needs an update after this merge. Expect for 1-2 days from now, work has been quite busy though 😅 

Cheers!

**Comment by fazaghifari** [comment]
Done https://pypi.org/project/sobolsampling/ 😄

**Pull request merged**
